#!/bin/sh

sep="$1"
src="$2"
dst="$3"

mkdir -p "$dst"
find "$src" -name '*.git' -prune -printf '%P\n' | while read repo; do
  echo "$repo"
  newname=$(echo $repo | tr / "$sep")
  rm -rf "$dst/$newname"
  cp -R "$src/$repo" "$dst/$newname"
done

